language: rust

rust:
  - nightly

os:
  - osx
  - linux
  - windows

install:
  - rustup component add rust-src
  - cargo xbuild --version || cargo install cargo-xbuild
  - bootimage --version    || cargo install bootimage --version "^0.5.0"
  - bootimage build --verbose

script:
  - bootimage test --verbose

cache: cargo    # cache Cargo packages
