language: rust
rust:
  - nightly
os:
  - osx
  - linux
  - windows
matrix:
  fast_finish: true
script:
  - cargo install cargo-xbuild
  - cargo install bootimage --version "^0.5.0"
  - bootimage build --verbose
  - bootimage test --verbose
